# Generated by Django 6.0.3 on 2026-06-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_alter_todo_options_category_user_todo_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Past'), (1, "O'rta"), (2, 'Yuqori')], default=1, max_length=10),
        ),
    ]
